### ISSUE TITLE
Customized conf.php not loaded

### ISSUE THREAD

**Issue by shelumiel** [PrivateBin/docker-nginx-fpm-alpine#62]
Basically, the same issue as in [#60](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/60#issue-969233604): The latest Docker images don't correctly load the customized conf.php file (mounted to /srv/cfg/conf.php).

I had the same issue about a month ago, which was fixed after a specific update, then having another one recently.
I also tried to modify the file/folder permissions (UID 65534 / GID 82). I suppose there is a problem inside the container images, which prevents it from loading external config files.

**Comment by elrido** [comment]
As indicated in #60, please use the tools at your disposal to check the permissions as seen from applications running inside of the container. Do you see the expected permissions when running an `ls -l`inside the container? Can you read the file using `cat` from inside the container?
```
docker exec <insert the running container ID or name here> cat srv/cfg/conf.php
```
As per the README, you need to set the permissions on the volume directory, not just the file and you may have to calculate the custom UID/GID numbers if you do use the "userns-remap" feature:
> Note that the volume mounted must be owned by UID 65534 / GID 82. If you run the container in a docker instance with "userns-remap" you need to add your subuid/subgid range to these numbers.
I'm unable to reproduce the issue locally with the 1.3.5 image or the latest one. The demo instance on privatebin.net uses a configuration file, runs the 1.3.5 image and is using the "userns-remap" feature.

If you can provide more diagnostics, I'm happy to help you make sense of them.

**Comment by shelumiel** [comment]
Thank you so much for your prompt reply.

With running an ls -l for the cfg directory inside the container, I see the following:

> -rwxrwxrwx    1 nobody   www-data      7452 Jul 11 10:36 conf.php

Also, inside the srv directory I see:

> drwxrwxr-x    1 nobody   www-data        34 Aug 17 03:12 cfg
> drwxrwxrwx    1 nobody   www-data       130 Aug 17 03:12 data
> drwxrwxr-x    1 nobody   www-data       284 Aug 15 19:28 lib
> drwxrwxr-x    1 nobody   www-data        60 Aug 15 19:28 tpl
> drwxrwxr-x    1 nobody   www-data       188 Aug 15 19:28 vendor

However, using cat, I get the following error (both inside and outside the container):

> cat: can't open 'srv/cfg/conf.php': No such file or directory

Is this still a permission issue? What can I try next? I'm not sure whether the docker instance is run with "userns-remap" on a Synology NAS. However, I know my own UID and GID.

By the way, I've used "privatebin/nginx-fpm-alpine:latest" for almost two years so far without making any change after the first few weeks. I hadn't seen this problem previously, and I only saw it first appearing about a month ago which was automatically resolved after updating the image (I'm employing "watchtower" to auto-update my containers). I suppose only some specific updates have this issue.

**Comment by elrido** [comment]
We can probably rule out a permission issue, because your ls inside the container was able to resolve the UID & GID into user and group names, so they are set to the expected values.

For the cat command, did you omit the first slash of the path on purpose? The [working directory in the container is /var/www](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L86), so it won't be able to open the file from there, using a relative path (one that doesn't start with a forward slash).

If your cat command works with the full path, then it is not a permission issue and the file should be readable to the php-fpm process.

We did have an issue with a configuration file not being read in the "nightly" & "latest" images produced between 3rd and 6th of July, see #50. Is it possible your Synology is "stuck" on that older "latest" image?

**Comment by shelumiel** [comment]
With running "cat /srv/cfg/conf.php"  inside the container, I can now see the exact content of my customized conf.php. I guess it means that the container can load the mounted config file but not apply the customization settings.

Watchtower automatically checks and applies updates to each container. For me, it happens every 24 hours, and I don't think I'm stuck on the older latest images. In fact, I even manually re-downloaded and re-deployed the latest image several hours ago, as you can see in the timestamps of the directories above. Is there anything I can still try at my end?

Thank you as always for providing this awesome paste tool! :)

**Comment by elrido** [comment]
Well, as I can't reproduce this issue on my end and you ruled out it is an old image with a known issue, we have to assume it is specific to your environment. You could try to attach a little PHP script or such into a location in /var/www to see what happens if PHP is accessing the configuration file. For example, something along the lines of:
```
<?php
error_reporting(E_ALL);
var_dump(
    file_get_contents('/srv/cfg/conf.php')
);
```

Then, call that file's URL via curl or in your browser - if it does read back the configuration file, it's neither the image nor the php-fpm process.

Finally, it might also be a cache in your browser or the webserver in front of the container that delivers an old version without the changes. That is tricky to debug, but you will know your setup best and can validate this at every stage of the request.

**Comment by rugk** [comment]
Just make sure to **delete** that file after testing, because it prints sensitive data to any user. :wink:

**Comment by shelumiel** [comment]
I confirmed PHP in the container could access the configuration file via the given PHP script.

Just in case, I also tried with the **edge** as well as the **nightly** images, still having the same problem at this point.

Like in [#60](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/60#issuecomment-898710496), I ended up using the older 1.3.5 image, which was uploaded a month ago and doesn't have the issue. I suppose the post author has the same case as me, and I want to see whether there are any other users having this problem as well.

I'll retry with the **latest** image when a new one is available. Thank you again for your kind help! :)

**Comment by elrido** [comment]
Some explanation on the "latest" image may be required: It is generated automatically as part of the "nightly" run. So a new image gets generated, even when there are no changes in the configurations of this project.

I don't know what we would need to change, as we have exhausted all diagnostics that I can think off and you have shown that the file has the right permissions and php scripts can read it, so privatebin will do so as well. Still, you don't see the right content. Did you investigate your webservers and browsers cache and eliminate those as showing you the wrong content? Can you maybe bypass these, i.e. using a browser session in a different user profile on the same device or using a different device? Can you somehow bypass the webserver on your Synology, i.e. via an ssh prot forwarding, to verify that the privatebin service is returning the content you see?

**Comment by shelumiel** [comment]
I have tried everything you mentioned.

I checked my webserver, restarted the Synology NAS, cleared the browser caches, accessed through other browsers and Incognito modes, tried with multiple PC and mobile devices in different networks, bypassed the reverse proxy server, and accessed from the internal network without port forwarding. I even modified the conf.php to turn off some PrivateBin options that might be related to the issue (ex. basepath, httpwarning, header = X_FORWARDED_FOR).

Every attempt failed, but again, once I re-download and re-deploy the older 1.3.5 image, everything works fine. The only thing I can suspect at this point is that some components inside the latest/nightly images (ex. nginx, php-fpm) have recently been updated, causing conflicts with my specific environment, as long as there are no other users experiencing the same issue (besides the post author in [#60](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/60)).

Since you can't reproduce this issue to find what to fix even after many efforts, I'll wait until there are further updates for the image components. If the issue is somehow resolved in the future, I'll definitely let you know here. I really appreciate your kind and patient help! wink

**Comment by elrido** [comment]
Had an idea this morning that did let me finally reproduce the issue. I'm using a shell script for my local testing of the image that I keep expanding with different ways of running the image and testing the results when issues get reported, to prevent regressions on other cases. While working on #50 I did set the new `CONFIG_PATH` environment variable to my existing test cases, but forgot to add a case to test the absence of it. Long story short, the issue I believed to have been fixed in #50 did resurface, as you reported, but I failed to reproduce it because my script masked the issue when that variable is not set. I apologize for the time you spent digging, because I didn't properly test the issue as reported.

The issue stems from us telling php-fpm to clear all environment variables (there had been many security issues in php in the past, caused by environment variables being abused to inject malicious code), but then select some of them to get passed down, like so:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/9e7cc388b770a5a7f6e508bbec5048630508f7be/etc/php8/php-fpm.d/zz-docker.conf#L19
If that variable is unset, it will get set, but be an empty string. In the php code of privatebin we only check for the variable being set and if it is we won't look at the default location for the configuration file, so the file you attached gets ignored.

I'll do another workaround to pass down the environment variable correctly using the s6-envdir tool - s6-linux-init deliberately clears all environment variables to prevent security issues, but it has an option to store them in files and the s6-envdir tool can be used to read them back in, before calling php-fpm, so they can get picked up, filtered and exposed to the php environment.

I'll also create a branch with some changes to the logic of the `CONFIG_PATH` handling over in the main project. Since this will only get picked up with a future privatebin release into the container image, we still need to retain the [above workaround](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/9e7cc388b770a5a7f6e508bbec5048630508f7be/Dockerfile#L8) (having that variable being defined to a default value in the container image) for the interim.

**Comment by shelumiel** [comment]
I really appreciate your detailed explanation. I'm glad to be a little help for the PrivateBin community to find and fix this issue.
I'll let you know how it goes once I try the new image. :wink:

**Comment by stefanman125** [comment]
I'm having the same issue and wanted to join the thread. 
I have setup PrivateBin using docker compose and don't see my new config changes being applied after recreating the stack. I have confirmed that my new config is being mounted inside the container, and that $CONFIG_PATH is empty. 
Hopefully the new merged image gets uploaded to dockerhub soon, this application is great.

**Comment by shelumiel** [comment]
The latest image has just been applied to my container via Watchtower, and the issue has gone away.
Everything works perfectly now! Again, I really appreciate your time and efforts. :blush:

**Comment by stefanman125** [comment]
Hmmm, this issue still seems to be haunting me, even after specifying the `latest` tag in my compose file. Is there anything else I can do to troubleshoot this? I made sure to specify `--build` when bringing up the compose services, and checked the container itself to see my config successfully copied and the `CONFIG_PATH` environment variable blank.

**Comment by elrido** [comment]
@stefanman125 Make sure you're not using a locally cached image, by running a docker(-compose) pull on the image/service name.

You can also check the contents of /etc/s6/services/php-fpm8/run inside the image and compare it with the change in fcfa332495521f20299d0770039a4ed1412d69ea to ensure you've got the changed image and check that the `CONFIG_PATH` is NOT blank (that would cause the bug to be triggered that we fixed in https://github.com/PrivateBin/PrivateBin/pull/829 for the next release of PrivateBin), but rather set to `/srv/cfg` (the default):
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/fcfa332495521f20299d0770039a4ed1412d69ea/Dockerfile#L8

**Comment by stefanman125** [comment]
@elrido Thanks! It worked! I deleted my local image by running `docker image rm privatebin/nginx-fpm-alpine:latest`, and then just brought up the compose file and it pulled the new image with my customized config applied. Not sure why it doesn't automatically  download the new image since it is tagged latest and there are changes.
